#@ load("@ytt:data","data")
---
service:
  filters:
  #@ if/end data.values.serviceStripPrefixEnabled:
  - #@ 'StripPrefix=' + data.values.serviceStripPrefixValue
  pathPrefix: #@ data.values.servicePredicatePath
openapi:
  location: https://cp.homelab.fynesy.com/api-docs
routes: #@ data.values.routesArray