#@ load("@ytt:data","data")
---
service:
  filters: #@ data.values.serviceFilters
  pathPrefix: #@ data.values.servicePredicatePath
openapi:
  location: #@ data.values.serviceOpenApiUrl
routes: #@ data.values.routesArray